### ISSUE TITLE
Reducing duplicate CSS styles

### ISSUE THREAD

**Issue by jim-rosales** [bdarboe/prj-rev-bwfs-dasmoto#3]
You did an excellent job applying the background colors to your various H2 elements and the styles they are shared efficiently. 

Another area you can do the same is in applying the font all your elements use. For example, your H1, H2, and span elements use the Helvetica font. Instead of applying the font individually and repeating the line of code three times you can do the following:

```CSS
h1,
h2,
span,
p { /** Added the p tag so the font is consistent throughout the page **/ 
  font-family: "Helvetica", serif; /** It's best practice to also include a fall back (backup generic) font **/
}
```
https://github.com/bdarboe/prj-rev-bwfs-dasmoto/blob/329c40aa90d1d96b844d367dda529dd6c1d20db8/DasmotoArts/resources/style.css#L1-L33
